# Generated by Django 5.0.1 on 2024-01-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=200)),
                ("frequency", models.IntegerField(default=1, max_length=7)),
                ("start_date", models.DateField()),
                ("goal_date", models.DateField()),
                ("completed", models.BooleanField(default=False)),
                ("streak", models.IntegerField(default=0, max_length=7)),
            ],
        ),
    ]
